// stories/components/vue/QtiItem.vue
<template>
  <div ref="containerRef" class="qti-item-container"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, watch } from 'vue';
import { QtiRenderer, type AssessmentResult } from '@qti-renderer/core';

interface Props {
  xml: string;
  onResponseChange?: (responses: Record<string, string | string[]>) => void;
  onAssessmentResult?: (result: AssessmentResult) => void;
}

const props = defineProps<Props>();

const containerRef = ref<HTMLElement | null>(null);
const rendererRef = ref<QtiRenderer | null>(null);

const mountRenderer = () => {
  if (!containerRef.value) {
    return;
  }

  try {
    // Create new renderer instance with feedback and validation enabled
    const renderer = new QtiRenderer(props.xml, {
      debug: false,
      showFeedback: true,
      validateXml: true,
    });
    rendererRef.value = renderer;

    // Render to container (async)
    renderer.render(containerRef.value).catch((error) => {
      console.error('Failed to render QTI item:', error);
      if (containerRef.value) {
        containerRef.value.innerHTML = `<div style="color: red; padding: 1rem;">
          Error rendering QTI item: ${error instanceof Error ? error.message : 'Unknown error'}
        </div>`;
      }
    });

    // Set up feedback callback
    renderer.onFeedbackUpdate(() => {
      if (props.onResponseChange && rendererRef.value) {
        props.onResponseChange(rendererRef.value.getResponses());
      }
      if (props.onAssessmentResult && rendererRef.value) {
        props.onAssessmentResult(rendererRef.value.processResponses());
      }
    });
  } catch (error) {
    console.error('Failed to create QTI renderer:', error);
    if (containerRef.value) {
      containerRef.value.innerHTML = `<div style="color: red; padding: 1rem;">
        Error creating QTI renderer: ${error instanceof Error ? error.message : 'Unknown error'}
      </div>`;
    }
  }
};

onMounted(() => {
  mountRenderer();
});

onBeforeUnmount(() => {
  if (rendererRef.value) {
    rendererRef.value = null;
  }
});

watch(() => props.xml, () => {
  if (containerRef.value) {
    containerRef.value.innerHTML = '';
    mountRenderer();
  }
});
</script>

// packages/qti-react/src/QtiItem.tsx
import React, { useEffect, useRef, useState } from "react";
import { QtiRenderer, type AssessmentResult } from "@qti-renderer/core";

/**
 * React wrapper component for QTI renderer
 *
 * This component bridges React and the framework-agnostic QTI renderer.
 * It uses useEffect to mount the renderer when the component mounts or
 * when the XML changes, and useRef to maintain a reference to the
 * container DOM element.
 *
 * Design decision: We don't try to make the renderer React-aware.
 * Instead, we mount it into a container div and let it manage its own DOM.
 */
export interface QtiItemProps {
  xml: string;
  onResponseChange?: (responses: Record<string, string | string[]>) => void;
  onAssessmentResult?: (result: AssessmentResult) => void;
}

export function QtiItem({
  xml,
  onResponseChange,
  onAssessmentResult,
}: QtiItemProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const rendererRef = useRef<QtiRenderer | null>(null);
  const [, forceUpdate] = useState(0);

  useEffect(() => {
    if (!containerRef.current) {
      return;
    }

    try {
      // Create new renderer instance with feedback and validation enabled
      const renderer = new QtiRenderer(xml, {
        debug: false,
        showFeedback: true,
        validateXml: true,
      });
      rendererRef.current = renderer;

      // Render to container (async)
      renderer.render(containerRef.current).catch((error) => {
        console.error("Failed to render QTI item:", error);
        if (containerRef.current) {
          containerRef.current.innerHTML = `<div style="color: red; padding: 1rem;">
            Error rendering QTI item: ${
              error instanceof Error ? error.message : "Unknown error"
            }
          </div>`;
        }
      });

      // Set up feedback callback to trigger re-render
      renderer.onFeedbackUpdate(() => {
        forceUpdate((prev) => prev + 1);
        if (onResponseChange && rendererRef.current) {
          onResponseChange(rendererRef.current.getResponses());
        }
        if (onAssessmentResult && rendererRef.current) {
          onAssessmentResult(rendererRef.current.processResponses());
        }
      });
    } catch (error) {
      console.error("Failed to create QTI renderer:", error);
      if (containerRef.current) {
        containerRef.current.innerHTML = `<div style="color: red; padding: 1rem;">
          Error creating QTI renderer: ${
            error instanceof Error ? error.message : "Unknown error"
          }
        </div>`;
      }
    }
  }, [xml, onResponseChange, onAssessmentResult]);

  return <div ref={containerRef} className="qti-item-container" />;
}
