// stories/components/vue/QtiItem.vue
<template>
  <div ref="containerRef" class="qti-item-container"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, watch } from 'vue';
import { QtiRenderer } from '@qti-renderer/core';

interface Props {
  xml: string;
}

const props = defineProps<Props>();

const containerRef = ref<HTMLElement | null>(null);
const rendererRef = ref<QtiRenderer | null>(null);

const mountRenderer = () => {
  if (!containerRef.value) {
    return;
  }

  try {
    // Create new renderer instance with feedback and validation enabled
    const renderer = new QtiRenderer(props.xml, {
      debug: false,
      showFeedback: true,
      validateXml: true,
    });
    rendererRef.value = renderer;

    // Render to container (async)
    renderer.render(containerRef.value).catch((error) => {
      console.error('Failed to render QTI item:', error);
      if (containerRef.value) {
        containerRef.value.innerHTML = `<div style="color: red; padding: 1rem;">
          Error rendering QTI item: ${error instanceof Error ? error.message : 'Unknown error'}
        </div>`;
      }
    });
  } catch (error) {
    console.error('Failed to create QTI renderer:', error);
    if (containerRef.value) {
      containerRef.value.innerHTML = `<div style="color: red; padding: 1rem;">
        Error creating QTI renderer: ${error instanceof Error ? error.message : 'Unknown error'}
      </div>`;
    }
  }
};

onMounted(() => {
  mountRenderer();
});

onBeforeUnmount(() => {
  if (rendererRef.value) {
    rendererRef.value = null;
  }
});

watch(() => props.xml, () => {
  if (containerRef.value) {
    containerRef.value.innerHTML = '';
    mountRenderer();
  }
});
</script>

// stories/components/vanilla/QtiItem.tsx
import React, { useEffect, useRef } from 'react';
import { QtiRenderer } from '@qti-renderer/core';

interface VanillaQtiItemProps {
  xml: string;
}

export function VanillaQtiItem({ xml }: VanillaQtiItemProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const rendererRef = useRef<QtiRenderer | null>(null);

  useEffect(() => {
    if (!containerRef.current) {
      return;
    }

    try {
      const renderer = new QtiRenderer(xml, {
        debug: false,
        showFeedback: true,
        validateXml: true,
      });
      rendererRef.current = renderer;
      renderer.render(containerRef.current).catch((error) => {
        console.error('Failed to render QTI item:', error);
        if (containerRef.current) {
          containerRef.current.innerHTML = `<div style="color: red; padding: 1rem;">
            Error rendering QTI item: ${error instanceof Error ? error.message : 'Unknown error'}
          </div>`;
        }
      });

      return () => {
        rendererRef.current = null;
      };
    } catch (error) {
      console.error('Failed to create QTI renderer:', error);
      if (containerRef.current) {
        containerRef.current.innerHTML = `<div style="color: red; padding: 1rem;">
          Error creating QTI renderer: ${error instanceof Error ? error.message : 'Unknown error'}
        </div>`;
      }
    }
  }, [xml]);

  return (
    <div
      ref={containerRef}
      style={{
        width: '100%',
        maxWidth: '800px',
        padding: '20px',
      }}
      className="qti-item-container"
    />
  );
}
