// packages/qti-vanilla/src/QtiItem.tsx
import React, { useEffect, useRef } from "react";
import { QtiRenderer, type AssessmentResult } from "@qti-renderer/core";

export interface VanillaQtiItemProps {
  xml: string;
  onResponseChange?: (responses: Record<string, string | string[]>) => void;
  onAssessmentResult?: (result: AssessmentResult) => void;
}

/**
 * Vanilla JS wrapper component for QTI renderer
 * This is a React wrapper that uses the framework-agnostic QTI renderer directly
 */
export function VanillaQtiItem({
  xml,
  onResponseChange,
  onAssessmentResult,
}: VanillaQtiItemProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const rendererRef = useRef<QtiRenderer | null>(null);

  useEffect(() => {
    if (!containerRef.current) {
      return;
    }

    try {
      const renderer = new QtiRenderer(xml, {
        debug: false,
        showFeedback: true,
      });
      rendererRef.current = renderer;
      renderer.mount(containerRef.current);

      // Set up feedback callback
      renderer.onFeedbackUpdate(() => {
        if (onResponseChange && rendererRef.current) {
          onResponseChange(rendererRef.current.getResponses());
        }
        if (onAssessmentResult && rendererRef.current) {
          onAssessmentResult(rendererRef.current.processResponses());
        }
      });

      return () => {
        rendererRef.current = null;
      };
    } catch (error) {
      console.error("Failed to render QTI item:", error);
      if (containerRef.current) {
        containerRef.current.innerHTML = `<div style="color: red; padding: 1rem;">
          Error rendering QTI item: ${
            error instanceof Error ? error.message : "Unknown error"
          }
        </div>`;
      }
    }
  }, [xml, onResponseChange, onAssessmentResult]);

  return (
    <div
      ref={containerRef}
      style={{
        width: "100%",
        maxWidth: "800px",
        padding: "20px",
      }}
      className="qti-item-container"
    />
  );
}

// stories/components/vue/QtiItem.vue
<template>
  <div ref="containerRef" class="qti-item-container"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, watch } from 'vue';
import { QtiRenderer, type AssessmentResult } from '@qti-renderer/core';

interface Props {
  xml: string;
  onResponseChange?: (responses: Record<string, string | string[]>) => void;
  onAssessmentResult?: (result: AssessmentResult) => void;
}

const props = defineProps<Props>();

const containerRef = ref<HTMLElement | null>(null);
const rendererRef = ref<QtiRenderer | null>(null);

const mountRenderer = () => {
  if (!containerRef.value) {
    return;
  }

  try {
    // Create new renderer instance with feedback enabled
    const renderer = new QtiRenderer(props.xml, {
      debug: false,
      showFeedback: true,
    });
    rendererRef.value = renderer;

    // Mount to container
    renderer.mount(containerRef.value);

    // Set up feedback callback
    renderer.onFeedbackUpdate(() => {
      if (props.onResponseChange && rendererRef.value) {
        props.onResponseChange(rendererRef.value.getResponses());
      }
      if (props.onAssessmentResult && rendererRef.value) {
        props.onAssessmentResult(rendererRef.value.processResponses());
      }
    });
  } catch (error) {
    console.error('Failed to render QTI item:', error);
    if (containerRef.value) {
      containerRef.value.innerHTML = `<div style="color: red; padding: 1rem;">
        Error rendering QTI item: ${error instanceof Error ? error.message : 'Unknown error'}
      </div>`;
    }
  }
};

onMounted(() => {
  mountRenderer();
});

onBeforeUnmount(() => {
  if (rendererRef.value) {
    rendererRef.value = null;
  }
});

watch(() => props.xml, () => {
  if (containerRef.value) {
    containerRef.value.innerHTML = '';
    mountRenderer();
  }
});
</script>
